apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: dssp-pythontest-1
  description: Service dssp-pythontest-1

  annotations:
    github.com/project-slug: BackstageSSPPoC/dssp-pythontest-1
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: Backstage_SSP_PoC/dssp-pythontest-1/main
    argocd/app-name: dssp-pythontest-1-dev
    backstage.io/kubernetes-id: dssp-pythontest-1
    sonarqube.org/project-key: dssp-pythontest-1
    # prometheus.io/rule: "kube_pod_container_resource_requests{pod=~'dssp-pythontest-1.*'}|resource,kube_pod_container_status_running{pod=~'dssp-pythontest-1.*'}|container"
    # prometheus.io/alert: "all"
    # prometheus.io/labels: "namespace=dev"
    prometheus.io/rule: "kube_pod_container_resource_requests{pod=~'dssp-pythontest-1.*'}|resource,kube_pod_container_status_restarts_total{pod=~'dssp-pythontest-1.*'}|container"
    prometheus.io/alert: "KubePodCrashLooping,KubeDeploymentReplicasMismatch,KubePodNotReady,KubeContainerWaiting,KubeContainerOOMKilled,KubeDeploymentRolloutStuck"
    prometheus.io/labels: "namespace=dev"

spec:
  type: service
  owner: development
  lifecycle: experimental

# apiVersion: backstage.io/v1alpha1
# kind: Component

# metadata:
#   name: dssp-pythontest-1
#   description: Service dssp-pythontest-1

#   annotations:
#     github.com/project-slug: BackstageSSPPoC/dssp-pythontest-1
#     backstage.io/techdocs-ref: dir:.
#     jenkins.io/job-full-name: Backstage_SSP_PoC/dssp-pythontest-1/main
#     argocd/app-name: dssp-pythontest-1
#     backstage.io/kubernetes-id: dssp-pythontest-1
#     sonarqube.org/project-key: dssp-pythontest-1

# spec:
#   type: service
#   owner: development
#   lifecycle: experimental
